emotion_to_emoji = {
    "admiration" : '🤩',
    "amusement" : '🙂',
    "anger": '😤',
    "annoyance": '😒', 
    "approval": '👍',    
    "caring": '🤗',
    "confusion":'🤨',
    "curiosity": '👀',
    "desire": '🤑',
    "disappointment": '😔',
    "disapproval": '👎',
    "disgust": '🤢',
    "embarrassment":'😣',
    "excitement": '😃',
    "fear": '😱',
    "gratitude": "😚",
    "grief": "😭",    
    "joy": "😁",    
    "love": "🥰",    
    "nervousness": "😳",    
    "optimism": "👌",    
    "pride": "😎",    
    "realization": "🤓",    
    "relief": "😌",    
    "remorse": "😖",    
    "sadness" : "😓",    
    "surprise" : "😲",    
    "neutral" : "😐",
}

all_emotions = [
    "admiration",
    "amusement",
    "anger",    
    "annoyance",    
    "approval",    
    "caring",    
    "confusion",    
    "curiosity",    
    "desire",    
    "disappointment",    
    "disapproval",    
    "disgust",    
    "embarrassment",    
    "excitement",
    "fear",    
    "gratitude",    
    "grief",    
    "joy",    
    "love",    
    "nervousness",    
    "optimism",    
    "pride",    
    "realization",    
    "relief",    
    "remorse",    
    "sadness",    
    "surprise",    
    "neutral"
    ]

positive_emotions =  [
            "admiration",
            "amusement", 
            "approval", 
            "caring", 
            "curiosity",
            "desire", 
            "excitement", 
            "gratitude",
            "joy", 
            "love", 
            "optimism", 
            "pride", 
            "realization", 
            "relief", 
            "surprise"]

negative_emotions =  [   
            "anger",    
            "annoyance",       
            "confusion",    
            "disappointment",  
            "disapproval",    
            "disgust",    
            "embarrassment",
            "fear",    
            "grief",   
            "nervousness",   
            "remorse",    
            "sadness"
        ]


def is_positive_emotion(emotion: str) -> bool:
    return emotion in positive_emotions